{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nexus-repository-cleanup.serviceAccountName" . }}
  labels:
    {{- include "nexus-repository-cleanup.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
