# Default values for nexus-repository-cleanup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

image:
  # -- Registry to pull image from
  registry: ghcr.io
  # -- Image name to pull
  repository: skarzhevskyy/nexus-repository-cleanup
  tag: ""
  pullPolicy: IfNotPresent

# Image pull secrets
imagePullSecrets: []
# - name: myregistrykey

nexusRepositoryCleanup:
  rules: []   # With context of cleanup-rules.yml to create cleanupRules config map
  # or ref to an existing config map with rules created and maintained separately
  existingCleanupRulesConfigMapName: ""
  nexusUrl: ""
  credentialsSecretName: "" # optional with username password or token values that will be mapped to environment variables.
  dryRun: true # if true, the job will not delete any components, but will report what would be deleted.
  otherArguments: "--report-repositories-summary --report-top-groups" # to be passed to application.

cronjob:
  # -- Schedules the job to run using cron notation
  schedule: '0 1 * * *'  # At 01:00 every day
  # -- You can specify a time zone for a CronJob by setting timeZone to the name of a valid time zone. (starting with k8s 1.27) <https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#time-zones>
  timeZone: ''  # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for valid names
  # -- If it is set to true, all subsequent executions are suspended. This setting does not apply to already started executions.
  suspend: false
  # -- Annotations to set on the cronjob
  annotations: {}
  # -- Labels to set on the cronjob
  labels: {}
  # -- Set to Never to restart the job when the pod fails or to OnFailure to restart when a container fails
  podRestartPolicy: Never
  # -- Number of times to retry running the pod before considering the job as being failed
  jobBackoffLimit: 1
  # -- Amount of failed jobs to keep in history
  failedJobsHistoryLimit: ''
  # -- Amount of completed jobs to keep in history
  successfulJobsHistoryLimit: ''
  # -- Time to keep the job after it finished before automatically deleting it, Defaults to 1 day (24 hours).
  ttlSecondsAfterFinished: 86400

# See also env.JAVA_TOOL_OPTIONS
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi

env:
  - name: JAVA_TOOL_OPTIONS
    value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+ExitOnOutOfMemoryError"

envFrom: []
# Example:
# envFrom:
#   - configMapRef:
#       name: my-configmap
#   - secretRef:
#       name: my-secret

# Optional: serviceAccount, RBAC
serviceAccount:
  create: false
  name: default

pod:
  # -- Annotations to set on the pod
  annotations: {}
  # -- Labels to set on the pod
  labels: {}

# Pod security context and tolerations, node selectors
nodeSelector: {}
tolerations: []
affinity: {}

# -- Security contexts
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]

